export const TOURNAMENT_STATUS = {
  UPCOMING: "UPCOMING",
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const TOURNAMENT_FORMAT = {
  LEAGUE: "LEAGUE",
  KNOCKOUT: "KNOCKOUT",
  GROUP_AND_KNOCKOUT: "GROUP_AND_KNOCKOUT",
} as const;
